parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: 2022
  sourceType: module
  ecmaFeatures:
    jsx: true

env:
  browser: true
  node: true
  es2020: true

globals:
  graphql: true
  __PATH_PREFIX__: true

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:mdx/recommended
  - plugin:prettier/recommended

plugins:
  - react
  - react-hooks
  - '@typescript-eslint'

rules:
  no-unused-vars: 'warn'
  react/jsx-filename-extension: ['warn', { 'extensions': ['.tsx', '.jsx'] }]
  react/react-in-jsx-scope: 'off'
  react/jsx-one-expression-per-line: 'off'
  react-hooks/rules-of-hooks: 'error'
  react-hooks/exhaustive-deps: 'warn'
  object-curly-newline: 'off'
  # import/prefer-default-export: 'off'
  # import/extensions: 'ignorePackages'

settings:
  extensions: ['.js', '.jsx', '.ts', '.tsx', '.mdx']
  mdx/code-blocks: true
