parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: 2022
  sourceType: module
  ecmaFeatures:
    jsx: true

env:
  browser: true
  node: true
  es6: true
  es2020: true

globals:
  graphql: true
  __PATH_PREFIX__: true

extends:
  # - airbnb-base
  - airbnb
  - airbnb/hooks
  - plugin:@typescript-eslint/eslint-recommended
  - prettier
  - prettier/@typescript-eslint
  - prettier/react

plugins:
  - react
  - react-hooks
  - '@typescript-eslint'

rules:
  semi: ['error', 'never']
  react/jsx-filename-extension: ['warn', { 'extensions': ['.tsx', '.jsx'] }]
  react/react-in-jsx-scope: 'off'
  react/jsx-one-expression-per-line: ['warn', { 'allow': 'single-child' }]
  react/prop-types: 'off'
  react-hooks/rules-of-hooks: 'error'
  react-hooks/exhaustive-deps: 'warn'
  object-curly-newline: 'off'
  # graphql/template-strings:
  import/prefer-default-export: 'off'
  import/extensions: 'ignorePackages'

settings:
  ## fix "Unable to resolve path to module"
  ## https://github.com/benmosher/eslint-plugin-import#resolvers
  import/resolver:
    node:
      extensions: ['.js', '.jsx', '.ts', '.tsx']
      paths:
        - './'
