root: true
# Indicate this file is the root-level one used by the project and
# ESLint should not search beyond this directory for config files.

parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 'latest'
  ecmaFeatures:
    jsx: true

# `extends` tells ESLint that your config extends the given configurations.
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@eslint-react/recommended
  - plugin:react-hooks/recommended
  - plugin:prettier/recommended
  - plugin:mdx/recommended

# `plugins` tells ESLint to load these packages as a plugin.
plugins:
  - react-hooks
  - '@typescript-eslint'
  - '@stylistic'

rules:
  no-unused-vars: 'warn'
  '@eslint-react/jsx-filename-extension':
    - 'warn'
    - { 'extensions': ['.tsx', '.jsx'] }
  '@eslint-react/react-in-jsx-scope': 'off'
  '@eslint-react/jsx-one-expression-per-line': 'off'
  object-curly-newline: 'off'

settings:
  extensions: ['.js', '.jsx', '.ts', '.tsx', '.mdx']
  mdx/code-blocks: true
