name = "lqhuang-io"
pages_build_output_dir = "out"
compatibility_date = "2025-05-05"

[env.production.vars]
BLOG_REPO = "https://github.com/lqhuang/blog"
CONTENT_DIR = "./blog/"
NODE_VERSION = "22.17.0"
PNPM_VERSION = "10.13.1"
